services:
  therefore-sharer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: therefore-sharer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data/
    restart: always
